package dev.sysboot.core;

public enum EventKind {
  PHASE_STARTED,
  PHASE_COMPLETED,
  PHASE_FAILED,
  PHASE_BLOCKED,
  RESTART_REQUIRED,
  MODULE_STARTED,
  ITEM_STARTED,
  ITEM_COMPLETED,
  MODULE_COMPLETED,
  ERROR
}
