package dev.sysboot.core;

public enum ItemType {
  PACKAGE_ACTION,
  PACKAGE,
  APT_REPOSITORY,
  RPM_REPOSITORY,
  ZYPPER_REPOSITORY,
  PACMAN_REPOSITORY,
  FLATPAK,
  FLATPAK_REMOTE,
  SHELL_SCRIPT,
  COMPILED_BINARY,
  DOTBOT,
  DEFAULT_SHELL,
  OH_MY_ZSH,
  TOOLCHAIN,
  NERD_FONT,
  SHELL_RELOAD,
  SHELL_COMMAND,
  ASSERT,
  MANUAL,
  INTERRUPT,
  SDKMAN_PACKAGE
}
